// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coreDepartmantProject.Models;

#nullable disable

namespace coreDepartmantProject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240210093512_personalmig")]
    partial class personalmig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("coreDepartmantProject.Models.departmant", b =>
                {
                    b.Property<int>("deptid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deptid"), 1L, 1);

                    b.Property<string>("deptname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deptid");

                    b.ToTable("departmants");
                });

            modelBuilder.Entity("coreDepartmantProject.Models.personal", b =>
                {
                    b.Property<int>("personalid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personalid"), 1L, 1);

                    b.Property<string>("personallastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personalname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personalsehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personalid");

                    b.ToTable("personals");
                });
#pragma warning restore 612, 618
        }
    }
}
