// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coreDepartmantProject.Models;

#nullable disable

namespace coreDepartmantProject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240327154031_adminte")]
    partial class adminte
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("coreDepartmantProject.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<int>("Kullanici")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("coreDepartmantProject.Models.departmant", b =>
                {
                    b.Property<int>("deptid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deptid"), 1L, 1);

                    b.Property<string>("deptname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deptid");

                    b.ToTable("departmants");
                });

            modelBuilder.Entity("coreDepartmantProject.Models.personal", b =>
                {
                    b.Property<int>("personalid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personalid"), 1L, 1);

                    b.Property<int>("departdeptid")
                        .HasColumnType("int");

                    b.Property<string>("personallastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personalname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personalsehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personalid");

                    b.HasIndex("departdeptid");

                    b.ToTable("personals");
                });

            modelBuilder.Entity("coreDepartmantProject.Models.personal", b =>
                {
                    b.HasOne("coreDepartmantProject.Models.departmant", "depart")
                        .WithMany("personals")
                        .HasForeignKey("departdeptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depart");
                });

            modelBuilder.Entity("coreDepartmantProject.Models.departmant", b =>
                {
                    b.Navigation("personals");
                });
#pragma warning restore 612, 618
        }
    }
}
